# Generated by Django 6.0.2 on 2026-03-06 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guarantor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('citizenship_number', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Released', 'Released')], default='Active', max_length=10)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantors', to='loans.loan')),
                ('member', models.ForeignKey(blank=True, help_text='Optional: If guarantor is also a member', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guaranteed_loans', to='members.member')),
            ],
        ),
    ]
