# Generated by Django 6.0.2 on 2026-03-04 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cooperatives', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('citizenship_number', models.CharField(max_length=50, unique=True)),
                ('unique_system_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('blacklist_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='cooperatives.cooperative')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['citizenship_number'], name='members_mem_citizen_ba44af_idx'), models.Index(fields=['unique_system_id'], name='members_mem_unique__15a125_idx'), models.Index(fields=['blacklist_status'], name='members_mem_blackli_f0404b_idx')],
            },
        ),
    ]
