# Generated by Django 6.0.2 on 2026-03-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='unique_system_id',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
    ]
